os:
  - linux

language: php

php:
  - '7.2'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - cp BACKEND/.env.travis BACKEND/.env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - apt-get install php7.2-xml
  - mysql -u root -e 'CREATE DATABASE credpal;'
  - mysql -u root credpal < tests/credpal.sql
script:
  - cd  BACKEND/ && vendor/bin/phpunit --coverage-text
